In [1]:
import pandas as pd
%matplotlib inline
df=pd.read_csv('Faili query-FH_set1_325indiv_genePLUS_medicationsConsolid-20220127.csv',sep=";")
oige=pd.read_csv('20211209_VARV_isikud-FH_set1-325indiv-genePLUS-BMI_person_portrait-20211122_MN.csv',sep=";")

In [2]:
print(df.head())
df

  Person skood  Person gender code  Person birthYear Person agreementDate  \
0   EGVD000064                   2              1972           2007-11-29
1   EGVD000064                   2              1972           2007-11-29
2   EGVD000064                   2              1972           2007-11-29
3   EGVD000064                   2              1972           2007-11-29
4   EGVD000064                   2              1972           2007-11-29

   Person ageToday  Person deathYear MedicationConsolidated atc code  \
0             49.0               NaN                         D01AE15
1             49.0               NaN                         D01AE16
2             49.0               NaN                         M01AX05
3             49.0               NaN                         J01CR02
4             49.0               NaN                         R01AD08

  MedicationConsolidated atc name MedicationConsolidated medicament  \
0                     terbinafiin                               NaN
1                      amorolfiin                           LOCERYL
2                    glükoosamiin                           ARTHRYL
3    amoksitsilliin+klavulaanhape                         AUGMENTIN
4                     flutikasoon    FLIXONASE AQUEOUS NASAL SPRAY

  MedicationConsolidated earliestDate MedicationConsolidated latestDate  \
0                          2004-03-25                        2004-03-25
1                          2004-12-08                        2004-12-08
2                          2005-05-19                        2005-05-19
3                          2005-07-22                        2005-07-22
4                          2005-10-22                        2005-10-22

   MedicationConsolidated medicationDurationMonth  \
0                                             0.0
1                                             0.0
2                                             0.0
3                                             0.0
4                                             0.0

   MedicationConsolidated numberOfSources  \
0                                       1
1                                       1
2                                       1
3                                       1
4                                       1

   MedicationConsolidated numberOfRows  MedicationConsolidated rowsAnswerset  \
0                                    2                                     0
1                                    1                                     0
2                                    1                                     0
3                                    1                                     0
4                                    1                                     0

   MedicationConsolidated rowsHif  \
0                               2
1                               1
2                               1
3                               1
4                               1

   MedicationConsolidated rowsEhealthEpicrisis  \
0                                            0
1                                            0
2                                            0
3                                            0
4                                            0

   MedicationConsolidated rowsTuh  MedicationConsolidated rowsNemc
0                               0                                0
1                               0                                0
2                               0                                0
3                               0                                0
4                               0                                0

,Person skood,Person gender code,Person birthYear,Person agreementDate,Person ageToday,Person deathYear,MedicationConsolidated atc code,MedicationConsolidated atc name,MedicationConsolidated medicament,MedicationConsolidated earliestDate,MedicationConsolidated latestDate,MedicationConsolidated medicationDurationMonth,MedicationConsolidated numberOfSources,MedicationConsolidated numberOfRows,MedicationConsolidated rowsAnswerset,MedicationConsolidated rowsHif,MedicationConsolidated rowsEhealthEpicrisis,MedicationConsolidated rowsTuh,MedicationConsolidated rowsNemc
0,EGVD000064,2,1972,2007-11-29,49.0,NaN,D01AE15,terbinafiin,NaN,2004-03-25,2004-03-25,0.0,1,2,0,2,0,0,0
1,EGVD000064,2,1972,2007-11-29,49.0,NaN,D01AE16,amorolfiin,LOCERYL,2004-12-08,2004-12-08,0.0,1,1,0,1,0,0,0
2,EGVD000064,2,1972,2007-11-29,49.0,NaN,M01AX05,glükoosamiin,ARTHRYL,2005-05-19,2005-05-19,0.0,1,1,0,1,0,0,0
3,EGVD000064,2,1972,2007-11-29,49.0,NaN,J01CR02,amoksitsilliin+klavulaanhape,AUGMENTIN,2005-07-22,2005-07-22,0.0,1,1,0,1,0,0,0
4,EGVD000064,2,1972,2007-11-29,49.0,NaN,R01AD08,flutikasoon,FLIXONASE AQUEOUS NASAL SPRAY,2005-10-22,2005-10-22,0.0,1,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12628,EGVD996458,2,1996,2018-05-23,25.0,NaN,G03AC08,etonogestreel,NaN,2018-05-16,2018-05-16,0.0,1,1,0,0,1,0,0
12629,EGVD996458,2,1996,2018-05-23,25.0,NaN,D10AF02,erütromütsiin,AKNEFUG-EL,2018-07-18,2018-07-18,0.0,1,1,0,1,0,0,0
12630,EGVD996458,2,1996,2018-05-23,25.0,NaN,D10AF02,erütromütsiin,NaN,2019-06-18,2019-06-18,0.0,1,1,0,0,1,0,0
12631,EGVD996458,2,1996,2018-05-23,25.0,NaN,D10AF02,erütromütsiin,ERYTHROMYCINE BAILLEUL 4%,2019-07-25,2020-03-24,8.0,1,2,0,2,0,0,0
12632,EGVD996458,2,1996,2018-05-23,25.0,NaN,S01AA01,klooramfenikool,OFTAN AKVAKOL,2020-11-03,2020-11-03,0.0,1,1,0,1,0,0,0

In [3]:
print(oige.head())
oige

  Person skood       Scode Vcode with variant All_Vcodes SNP array geno  \
0   EGVD000064  EGVD000064             V12985     V12985            0/1
1   EGVD000081  EGVD000081             V07285     V07285            0/1
2   EGVD000927  EGVD000927             V46059     V46059            0/1
3   EGVD000940  EGVD000940             V23156        NaN            NaN
4   EGVD002100  EGVD002100             V14661     V14661            0/1

       rs_name      POS_GRCh37  REF  ALT  Gene Nucleotide change
0    rs5742904   chr2:21229160    C    T  APOB        c.10580G>A
1    rs5742904   chr2:21229160    C    T  APOB        c.10580G>A
2    rs5742904   chr2:21229160    C    T  APOB        c.10580G>A
3  rs766474188  chr19:11223954  NaN  NaN  LDLR        c.1187 G>C
4    rs5742904   chr2:21229160    C    T  APOB        c.10580G>A

,Person skood,Scode,Vcode with variant,All_Vcodes,SNP array geno,rs_name,POS_GRCh37,REF,ALT,Gene,Nucleotide change
0,EGVD000064,EGVD000064,V12985,V12985,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
1,EGVD000081,EGVD000081,V07285,V07285,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
2,EGVD000927,EGVD000927,V46059,V46059,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
3,EGVD000940,EGVD000940,V23156,NaN,NaN,rs766474188,chr19:11223954,NaN,NaN,LDLR,c.1187 G>C
4,EGVD002100,EGVD002100,V14661,V14661,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
...,...,...,...,...,...,...,...,...,...,...,...
320,EGVD990344,EGVD990344,VSPGBT,VSPGBT,0/1,rs761954844,chr19:11221373,G,A,LDLR,c.986G>A
321,EGVD991216,EGVD991216,V5FC2X,V5FC2X,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
322,EGVD994088,EGVD994088,VPT4RR,VPT4RR,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
323,EGVD996176,EGVD996176,VLSQBQ,VLSQBQ,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
324,EGVD996458,EGVD996458,VKSAU8,VKSAU8,0/1,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A

In [7]:
#FH table equivalence

#df1=pd.DataFrame({'x':df['POS ch37'],'NCBI':'', 'VarMap':''})

df1=df.copy()

df1['Vcode']=''
df1['rs_name']=''
df1['POS_GRCh37']=''
df1['REF']=''
df1['ALT']=''
df1['Gene']=''
df1['Nucleotide change']=''

for i in range (len(df1)):
    skood=df1['Person skood'][i]
    row_numbers=oige[oige['Person skood'] == skood].index[0]
    df1['Vcode'][i]=oige['Vcode with variant'][row_numbers]
    df1['rs_name'][i]=oige['rs_name'][row_numbers]
    df1['POS_GRCh37'][i]=oige['POS_GRCh37'][row_numbers]
    df1['REF'][i]=oige['REF'][row_numbers]
    df1['ALT'][i]=oige['ALT'][row_numbers]
    df1['Gene'][i]=oige['Gene'][row_numbers]
    df1['Nucleotide change'][i]=oige['Nucleotide change'][row_numbers]
    #chrom=str(df['CHROM'][i])
    #pos=str(int(df['POS ch37'][i]))
    #df1.NCBI[i]="chr" + chrom + ":" + pos
    #print(row_numbers,skood)

df1

<ipython-input-7-b6a360b362bd>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Vcode'][i]=oige['Vcode with variant'][row_numbers]
<ipython-input-7-b6a360b362bd>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['rs_name'][i]=oige['rs_name'][row_numbers]
<ipython-input-7-b6a360b362bd>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['POS_GRCh37'][i]=oige['POS_GRCh37'][row_numbers]
<ipython-input-7-b6a360b362bd>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['REF'][i]=oige['REF'][row_numbers]
<ipython-input-7-b6a360b362bd>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ALT'][i]=oige['ALT'][row_numbers]
<ipython-input-7-b6a360b362bd>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Gene'][i]=oige['Gene'][row_numbers]
<ipython-input-7-b6a360b362bd>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Nucleotide change'][i]=oige['Nucleotide change'][row_numbers]

,Person skood,Person gender code,Person birthYear,Person agreementDate,Person ageToday,Person deathYear,MedicationConsolidated atc code,MedicationConsolidated atc name,MedicationConsolidated medicament,MedicationConsolidated earliestDate,...,MedicationConsolidated rowsEhealthEpicrisis,MedicationConsolidated rowsTuh,MedicationConsolidated rowsNemc,Vcode,rs_name,POS_GRCh37,REF,ALT,Gene,Nucleotide change
0,EGVD000064,2,1972,2007-11-29,49.0,NaN,D01AE15,terbinafiin,NaN,2004-03-25,...,0,0,0,V12985,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
1,EGVD000064,2,1972,2007-11-29,49.0,NaN,D01AE16,amorolfiin,LOCERYL,2004-12-08,...,0,0,0,V12985,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
2,EGVD000064,2,1972,2007-11-29,49.0,NaN,M01AX05,glükoosamiin,ARTHRYL,2005-05-19,...,0,0,0,V12985,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
3,EGVD000064,2,1972,2007-11-29,49.0,NaN,J01CR02,amoksitsilliin+klavulaanhape,AUGMENTIN,2005-07-22,...,0,0,0,V12985,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
4,EGVD000064,2,1972,2007-11-29,49.0,NaN,R01AD08,flutikasoon,FLIXONASE AQUEOUS NASAL SPRAY,2005-10-22,...,0,0,0,V12985,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12628,EGVD996458,2,1996,2018-05-23,25.0,NaN,G03AC08,etonogestreel,NaN,2018-05-16,...,1,0,0,VKSAU8,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
12629,EGVD996458,2,1996,2018-05-23,25.0,NaN,D10AF02,erütromütsiin,AKNEFUG-EL,2018-07-18,...,0,0,0,VKSAU8,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
12630,EGVD996458,2,1996,2018-05-23,25.0,NaN,D10AF02,erütromütsiin,NaN,2019-06-18,...,1,0,0,VKSAU8,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
12631,EGVD996458,2,1996,2018-05-23,25.0,NaN,D10AF02,erütromütsiin,ERYTHROMYCINE BAILLEUL 4%,2019-07-25,...,0,0,0,VKSAU8,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A
12632,EGVD996458,2,1996,2018-05-23,25.0,NaN,S01AA01,klooramfenikool,OFTAN AKVAKOL,2020-11-03,...,0,0,0,VKSAU8,rs5742904,chr2:21229160,C,T,APOB,c.10580G>A

In [10]:
df1.to_csv('20220206_VARV_FH_set1_325indiv_genePLUS_medicationsConsolid-20220127.csv',sep=",",header=True)

In [11]:
df1.to_excel('20220206_VARV_FH_set1_325indiv_genePLUS_medicationsConsolid-20220127.xlsx')